// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdylPJbwSb2b4NuY8DcmSQo4qDqgDQHqA',
    appId: '1:502105268327:web:a19f8daef4a0a305ceb4c2',
    messagingSenderId: '502105268327',
    projectId: 'firedrop-b56e3',
    authDomain: 'firedrop-b56e3.firebaseapp.com',
    storageBucket: 'firedrop-b56e3.firebasestorage.app',
    measurementId: 'G-XEH1CX8MXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1FQx_1OWKHUA2IdwAj3dwsls9NEsTENI',
    appId: '1:502105268327:android:d143a6a8f764af7cceb4c2',
    messagingSenderId: '502105268327',
    projectId: 'firedrop-b56e3',
    storageBucket: 'firedrop-b56e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMq5QG3597ZwnKlpabUwsSFGEzYUvhMcs',
    appId: '1:502105268327:ios:6b8a9e2e868f2314ceb4c2',
    messagingSenderId: '502105268327',
    projectId: 'firedrop-b56e3',
    storageBucket: 'firedrop-b56e3.firebasestorage.app',
    iosBundleId: 'com.example.firedrop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMq5QG3597ZwnKlpabUwsSFGEzYUvhMcs',
    appId: '1:502105268327:ios:6b8a9e2e868f2314ceb4c2',
    messagingSenderId: '502105268327',
    projectId: 'firedrop-b56e3',
    storageBucket: 'firedrop-b56e3.firebasestorage.app',
    iosBundleId: 'com.example.firedrop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdylPJbwSb2b4NuY8DcmSQo4qDqgDQHqA',
    appId: '1:502105268327:web:4562fc2cda0ce7c9ceb4c2',
    messagingSenderId: '502105268327',
    projectId: 'firedrop-b56e3',
    authDomain: 'firedrop-b56e3.firebaseapp.com',
    storageBucket: 'firedrop-b56e3.firebasestorage.app',
    measurementId: 'G-XL5H37TN4X',
  );
}
